services:
  siren:
    build:
      context: .
      dockerfile: Dockerfile
    image: siren-api:v1.2
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./models:/app/models:rw
